update to use only koajwt instead jwt + koajwt
Because in koajwt have all needing methods .sign and .verify
Edit require('.') to require('./index'), because not works in Linux Mint 14 (ubuntu 12.10). Neither tests and test-server -- Error: Cannot find module '.'