require('.') causing error, remove jsonwebtoken
Remove: jsonwebtoken, because use ./index, so koajwt, which have all methods that needs.
Change: require('.'), because causing `Error: Cannot find module '.'`.